import React from 'react';
import { Modal } from '../ui/Modal';
import { IconSparkles } from '../ui/Icons';
import { Skeleton, SkeletonText } from '../ui/Skeleton';
import { YEAR_MAX } from '../../config/constants';
import type { ScenarioResult } from '../../utils/analysis';

interface ScenarioModalProps {
    isOpen: boolean;
    isLoading: boolean;
    result: ScenarioResult | null;
    errorMessage?: string | null;
    onClose: () => void;
}

export const ScenarioModal: React.FC<ScenarioModalProps> = ({ isOpen, isLoading, result, errorMessage, onClose }) => {
    return (
        <Modal isOpen={isOpen} onClose={onClose} title={`Future Scenario: ${YEAR_MAX}`} size="md" layer="top">
            <div className="flex items-center gap-2 mb-6 text-xs text-gray-500">
                <IconSparkles size={14} className="text-purple-400" />
                <span>Generated by AI &middot; Based on O*NET Data</span>
            </div>

            {isLoading ? (
                <div className="space-y-6 py-6" role="status" aria-busy="true">
                    <div className="flex justify-center">
                        <div className="w-10 h-10 border-2 border-purple-500/40 border-t-purple-400 rounded-full animate-spin"></div>
                    </div>
                    <p className="text-center text-purple-300 text-sm">Generating scenario...</p>
                    <div className="space-y-4">
                        <Skeleton className="h-24 w-full rounded-lg" />
                        <SkeletonText lines={3} />
                    </div>
                </div>
            ) : errorMessage ? (
                <div className="text-center py-6 space-y-2 px-2">
                    <p className="text-red-400 text-sm leading-relaxed">{errorMessage}</p>
                </div>
            ) : result ? (
                <div className="space-y-6 animate-in fade-in duration-300">
                    <div className="border-l-2 border-purple-500/50 pl-4 py-1">
                        <p className="text-gray-200 leading-relaxed italic">"{result.story}"</p>
                    </div>

                    <div className="space-y-3">
                        <h4 className="text-xs font-semibold text-purple-400 uppercase tracking-wider">Key Shifts</h4>
                        <div className="space-y-2">
                            {result.keyChanges.map((change: string, i: number) => (
                                <div key={i} className="flex items-center gap-3 p-3 rounded-lg bg-white/[0.03] border border-white/[0.06]">
                                    <span className="text-purple-400 font-bold text-sm tabular-nums w-6">{String(i + 1).padStart(2, '0')}</span>
                                    <span className="text-gray-300 text-sm">{change}</span>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            ) : (
                <p className="text-red-400 text-sm">Failed to generate scenario. Check your Claude setup or try again.</p>
            )}
        </Modal>
    );
};
