import type { Job } from '../types';
import { DATA_SOURCES } from '../config/constants';

/** Traceable origin for a value shown in the UI (labor-market claims). */
export type DataProvenance =
    | 'BLS_OES'
    | 'BLS_OOH'
    | 'BLS_CPS'
    | 'ONET'
    | 'ONET_PROXY'
    | 'CLAUDE_TASK_SCORE'
    | 'CLAUDE_FORECAST'
    | 'COVERAGE_FORMULA'
    | 'UNAVAILABLE';

const PROVENANCE_LABEL: Record<DataProvenance, string> = {
    BLS_OES: 'How many people in the U.S. have this job today. Comes from the government’s main employment survey (BLS OES).',
    BLS_OOH: 'How much this job is expected to grow or shrink over the next 10 years (2024–2034). Comes from the government’s job outlook handbook (BLS OOH).',
    BLS_CPS: 'Live U.S. unemployment rate from the government’s household survey (BLS CPS). This is the national rate — not a count of people in this specific job.',
    ONET: 'The day-to-day tasks listed for this job. Comes from O*NET, a government job-description database.',
    ONET_PROXY: 'The day-to-day tasks listed for this job. Comes from O*NET, a government job-description database, using the closest matching occupation because O*NET does not publish a separate profile for this exact title.',
    CLAUDE_TASK_SCORE: 'For each task, AI rated how easy it is to automate and how much a human is still needed. Those scores power the risk numbers you see.',
    CLAUDE_FORECAST: 'A year-by-year prediction of how employment for this job may change, generated by AI and anchored to the government’s 10-year outlook (BLS OOH).',
    COVERAGE_FORMULA: 'An in-app score for how complete our data is for this job. Not an official government statistic.',
    UNAVAILABLE: 'This information is not available right now.',
};

export function provenanceLabel(p: DataProvenance): string {
    return PROVENANCE_LABEL[p];
}

/** Map bundled `dataSources` strings to provenance chips for the panel header. */
export function jobSourceProvenanceChips(job: Job): { key: string; label: string; provenance: DataProvenance }[] {
    const chips: { key: string; label: string; provenance: DataProvenance }[] = [];
    const src = new Set(job.dataSources);

    if (src.has(DATA_SOURCES.BLS_OES)) chips.push({ key: 'oes', label: 'OES', provenance: 'BLS_OES' });
    if (src.has(DATA_SOURCES.BLS_OOH)) chips.push({ key: 'ooh', label: 'OOH', provenance: 'BLS_OOH' });
    if (src.has(DATA_SOURCES.BLS_CPS)) chips.push({ key: 'cps', label: 'CPS', provenance: 'BLS_CPS' });
    // No State OES chip here by design. State-level OES backs the 2D map's
    // shading and Location Quotient; nothing on the detail panel is derived
    // from it, and it is a separate extract on its own vintage (constants.ts),
    // so showing it beside the national OES figure would imply the two agree
    // when they need not. The map states its own sources in MapView.
    if (src.has(DATA_SOURCES.ONET)) {
        // Alias roles carry real O*NET tasks borrowed from the closest
        // matching occupation, so they get the badge — with a tooltip that
        // says so rather than implying an exact O*NET profile exists.
        chips.push({ key: 'onet', label: 'O*NET', provenance: job.isAlias ? 'ONET_PROXY' : 'ONET' });
    }

    const hasClaudeTasks = job.tasks.some((t) => t.aiCapabilityScore > 0 || t.humanCriticalityScore > 0);
    if (hasClaudeTasks) chips.push({ key: 'ai', label: 'Claude tasks', provenance: 'CLAUDE_TASK_SCORE' });
    if (job.yearlyForecast?.length) chips.push({ key: 'fc', label: 'Claude forecast', provenance: 'CLAUDE_FORECAST' });

    return chips;
}

/**
 * Source line for the job detail panel footer. Applies the same rule as the
 * chips above so the badge row and the footer can never disagree about what
 * actually backs this panel.
 */
export function panelSourceList(job: Job): string[] {
    const sources = (job.dataSources ?? []).filter((s) => s !== DATA_SOURCES.BLS_STATE);
    return sources.length > 0 ? sources : ['Modeled'];
}

export function dataCoverageTooltip(): string {
    return 'Shows how complete our data is for this job. It is not a government accuracy rating.';
}
