import type { Job, JobStatus } from './types';

// DATA GENERATED BY REAL PIPELINE (BLS + O*NET)
export const initialJobs: Job[] = [
    {
        "id": "job-1",
        "cluster": "Business",
        "employment": 400000,
        "automationCostIndex": 0.58,
        "projectedGrowth": 1.3,
        "salaryVolatilityLabel": "High",
        "humanResilienceLabel": "High",
        "tasks": [
            {
                "name": "Campaign Logic",
                "aiCapabilityScore": 0.8,
                "humanCriticalityScore": 0.3
            },
            {
                "name": "Creative Strategy",
                "aiCapabilityScore": 0.3,
                "humanCriticalityScore": 0.9
            }
        ]
    },
    {
        "id": "job-2",
        "cluster": "Business",
        "employment": 120000,
        "automationCostIndex": 0.58,
        "projectedGrowth": 0.3,
        "salaryVolatilityLabel": "High",
        "humanResilienceLabel": "Very High",
        "tasks": [
            {
                "name": "Consumer Insight",
                "aiCapabilityScore": 0.5,
                "humanCriticalityScore": 0.8
            },
            {
                "name": "Trend Analysis",
                "aiCapabilityScore": 0.8,
                "humanCriticalityScore": 0.4
            }
        ]
    },
    {
        "id": "job-3",
        "cluster": "Business",
        "employment": 850000,
        "automationCostIndex": 0.46,
        "projectedGrowth": -0.9,
        "salaryVolatilityLabel": "High",
        "humanResilienceLabel": "High",
        "tasks": [
            {
                "name": "Requirements",
                "aiCapabilityScore": 0.6,
                "humanCriticalityScore": 0.6
            },
            {
                "name": "Process Mapping",
                "aiCapabilityScore": 0.7,
                "humanCriticalityScore": 0.3
            }
        ]
    },
    {
        "id": "job-4",
        "cluster": "Business",
        "employment": 300000,
        "automationCostIndex": 0.5,
        "projectedGrowth": -1,
        "salaryVolatilityLabel": "High",
        "humanResilienceLabel": "High",
        "tasks": [
            {
                "name": "Requirements",
                "aiCapabilityScore": 0.6,
                "humanCriticalityScore": 0.6
            },
            {
                "name": "Models",
                "aiCapabilityScore": 0.8,
                "humanCriticalityScore": 0.4
            }
        ]
    },
    {
        "id": "job-5",
        "cluster": "Business",
        "employment": 200000,
        "automationCostIndex": 0.58,
        "projectedGrowth": 1.5,
        "salaryVolatilityLabel": "High",
        "humanResilienceLabel": "High",
        "tasks": [
            {
                "name": "Portfolio Alloc.",
                "aiCapabilityScore": 0.85,
                "humanCriticalityScore": 0.3
            },
            {
                "name": "Client Advising",
                "aiCapabilityScore": 0.2,
                "humanCriticalityScore": 0.9
            }
        ]
    },
    {
        "id": "job-6",
        "cluster": "Business",
        "employment": 700000,
        "automationCostIndex": 0.54,
        "projectedGrowth": 0.4,
        "salaryVolatilityLabel": "High",
        "humanResilienceLabel": "High",
        "tasks": [
            {
                "name": "Data Analysis",
                "aiCapabilityScore": 0.9,
                "humanCriticalityScore": 0.2
            },
            {
                "name": "Client Strategy",
                "aiCapabilityScore": 0.3,
                "humanCriticalityScore": 0.9
            }
        ]
    },
    {
        "id": "job-7",
        "cluster": "Business",
        "employment": 300000,
        "automationCostIndex": 0.5,
        "projectedGrowth": -0.5,
        "salaryVolatilityLabel": "High",
        "humanResilienceLabel": "High",
        "tasks": [
            {
                "name": "Logistics Opt",
                "aiCapabilityScore": 0.9,
                "humanCriticalityScore": 0.2
            },
            {
                "name": "Vendor Rel.",
                "aiCapabilityScore": 0.4,
                "humanCriticalityScore": 0.8
            }
        ]
    },
    {
        "id": "job-8",
        "cluster": "Business",
        "employment": 150000,
        "automationCostIndex": 0.5,
        "projectedGrowth": -0.5,
        "salaryVolatilityLabel": "High",
        "humanResilienceLabel": "High",
        "tasks": [
            {
                "name": "Logistics Opt",
                "aiCapabilityScore": 0.9,
                "humanCriticalityScore": 0.2
            },
            {
                "name": "Vendor Rel.",
                "aiCapabilityScore": 0.4,
                "humanCriticalityScore": 0.8
            }
        ]
    },
    {
        "id": "job-9",
        "cluster": "Business",
        "employment": 1600000,
        "automationCostIndex": 0.5,
        "projectedGrowth": -0.5,
        "salaryVolatilityLabel": "High",
        "humanResilienceLabel": "High",
        "tasks": [
            {
                "name": "Code Gen",
                "aiCapabilityScore": 0.9,
                "humanCriticalityScore": 0.2
            },
            {
                "name": "Sys Arch",
                "aiCapabilityScore": 0.4,
                "humanCriticalityScore": 0.8
            }
        ]
    },
    {
        "id": "job-10",
        "cluster": "Business",
        "employment": 100000,
        "automationCostIndex": 0.46,
        "projectedGrowth": -1.4,
        "salaryVolatilityLabel": "High",
        "humanResilienceLabel": "High",
        "tasks": [
            {
                "name": "Optimization",
                "aiCapabilityScore": 0.9,
                "humanCriticalityScore": 0.2
            },
            {
                "name": "Model Def",
                "aiCapabilityScore": 0.5,
                "humanCriticalityScore": 0.7
            }
        ]
    },
    {
        "id": "job-11",
        "cluster": "Business",
        "employment": 400000,
        "automationCostIndex": 0.5,
        "projectedGrowth": 0.5,
        "salaryVolatilityLabel": "High",
        "humanResilienceLabel": "High",
        "tasks": [
            {
                "name": "Lead Gen",
                "aiCapabilityScore": 0.9,
                "humanCriticalityScore": 0.1
            },
            {
                "name": "Closing",
                "aiCapabilityScore": 0.2,
                "humanCriticalityScore": 0.9
            }
        ]
    },
    {
        "id": "job-12",
        "cluster": "Business",
        "employment": 400000,
        "automationCostIndex": 0.54,
        "projectedGrowth": 0.4,
        "salaryVolatilityLabel": "High",
        "humanResilienceLabel": "High",
        "tasks": [
            {
                "name": "Team Mgmt",
                "aiCapabilityScore": 0.3,
                "humanCriticalityScore": 0.9
            },
            {
                "name": "Forecasting",
                "aiCapabilityScore": 0.9,
                "humanCriticalityScore": 0.2
            }
        ]
    },
    {
        "id": "job-13",
        "cluster": "Business",
        "employment": 1400000,
        "automationCostIndex": 0.54,
        "projectedGrowth": -0.1,
        "salaryVolatilityLabel": "High",
        "humanResilienceLabel": "High",
        "tasks": [
            {
                "name": "Audit Logic",
                "aiCapabilityScore": 0.8,
                "humanCriticalityScore": 0.4
            },
            {
                "name": "Compliance",
                "aiCapabilityScore": 0.5,
                "humanCriticalityScore": 0.7
            }
        ]
    }
];

// --- REUSED LOGIC FROM PREVIOUS DATA.TS ---

export function getJobStatus(job: Job, year: number): JobStatus {
    const totalAiScore = job.tasks.reduce((sum, t) => sum + t.aiCapabilityScore, 0);
    const totalHumanScore = job.tasks.reduce((sum, t) => sum + t.humanCriticalityScore, 0);

    const avgAiCapability = job.tasks.length ? totalAiScore / job.tasks.length : 0.5;
    const avgHumanCriticality = job.tasks.length ? totalHumanScore / job.tasks.length : 0.5;

    // Rules
    const isHighRisk = avgAiCapability > 0.6 && job.automationCostIndex < 0.6;
    const isInsulated = avgHumanCriticality > 0.6;

    let riskScore = 0.5;
    let color = '#fbbf24'; // amber

    if (isHighRisk) {
        riskScore = 0.9;
        color = '#ef4444'; // red
    } else if (isInsulated) {
        riskScore = 0.1;
        color = '#22c55e'; // green
    }

    // Adaptation Logic
    const yearsPassed = year - 2025;
    const adaptationBoost = yearsPassed * 0.05;
    const projectedAiCap = Math.min(1, avgAiCapability + (yearsPassed * 0.02));
    const effectiveHumanCriticality = Math.min(1, avgHumanCriticality + adaptationBoost);
    
    // Recalculate for Year
    const isProjectedHighRisk = projectedAiCap > 0.7; // simplified
    const isProjectedInsulated = effectiveHumanCriticality > 0.65;

    if (isProjectedInsulated) {
        riskScore = 0.2;
        color = '#22c55e';
    } else if (isProjectedHighRisk) {
        riskScore = 0.9;
        color = '#ef4444';
    }

    return { riskScore, color };
}

export type TaskCategory = 'Automatable' | 'Augmentable' | 'Human-Critical';

export function getTaskCategory(task: { aiCapabilityScore: number; humanCriticalityScore: number }, year: number): TaskCategory {
    const yearsPassed = year - 2025;
    const adaptationBoost = yearsPassed * 0.05;
    const effectiveHumanScore = Math.min(1, task.humanCriticalityScore + adaptationBoost);
    
    if (task.aiCapabilityScore > 0.6 && effectiveHumanScore < 0.5) return 'Automatable';
    if (effectiveHumanScore > 0.6) return 'Human-Critical';
    return 'Augmentable';
}
